var annotated_dup =
[
    [ "pteros", null, [
      [ "Atom", "classpteros_1_1Atom.html", "classpteros_1_1Atom" ],
      [ "Atom_proxy", "classpteros_1_1Atom__proxy.html", "classpteros_1_1Atom__proxy" ],
      [ "Babel_wrapper", "classpteros_1_1Babel__wrapper.html", "classpteros_1_1Babel__wrapper" ],
      [ "Data_container", "structpteros_1_1Data__container.html", "structpteros_1_1Data__container" ],
      [ "DCD_file", "classpteros_1_1DCD__file.html", "classpteros_1_1DCD__file" ],
      [ "Distance_search_within", "classpteros_1_1Distance__search__within.html", "classpteros_1_1Distance__search__within" ],
      [ "Force_field", "classpteros_1_1Force__field.html", "classpteros_1_1Force__field" ],
      [ "Frame", "structpteros_1_1Frame.html", "structpteros_1_1Frame" ],
      [ "Frame_info", "structpteros_1_1Frame__info.html", "structpteros_1_1Frame__info" ],
      [ "GNM", "classpteros_1_1GNM.html", "classpteros_1_1GNM" ],
      [ "Grid", "classpteros_1_1Grid.html", "classpteros_1_1Grid" ],
      [ "GRO_file", "classpteros_1_1GRO__file.html", "classpteros_1_1GRO__file" ],
      [ "Gromacs_trajectory_file", "classpteros_1_1Gromacs__trajectory__file.html", "classpteros_1_1Gromacs__trajectory__file" ],
      [ "Histogram", "classpteros_1_1Histogram.html", "classpteros_1_1Histogram" ],
      [ "MOL2_file", "classpteros_1_1MOL2__file.html", "classpteros_1_1MOL2__file" ],
      [ "Mol_file", "classpteros_1_1Mol__file.html", "classpteros_1_1Mol__file" ],
      [ "Options", "classpteros_1_1Options.html", "classpteros_1_1Options" ],
      [ "PDB_file", "classpteros_1_1PDB__file.html", "classpteros_1_1PDB__file" ],
      [ "Periodic_box", "classpteros_1_1Periodic__box.html", "classpteros_1_1Periodic__box" ],
      [ "Pteros_error", "classpteros_1_1Pteros__error.html", "classpteros_1_1Pteros__error" ],
      [ "Selection", "classpteros_1_1Selection.html", "classpteros_1_1Selection" ],
      [ "Selection_parser", "classpteros_1_1Selection__parser.html", "classpteros_1_1Selection__parser" ],
      [ "System", "classpteros_1_1System.html", "classpteros_1_1System" ],
      [ "Task_plugin", "classpteros_1_1Task__plugin.html", "classpteros_1_1Task__plugin" ],
      [ "TNG_file", "classpteros_1_1TNG__file.html", "classpteros_1_1TNG__file" ],
      [ "Trajectory_reader", "classpteros_1_1Trajectory__reader.html", "classpteros_1_1Trajectory__reader" ],
      [ "TRR_file", "classpteros_1_1TRR__file.html", "classpteros_1_1TRR__file" ],
      [ "VMD_molfile_plugin_wrapper", "classpteros_1_1VMD__molfile__plugin__wrapper.html", "classpteros_1_1VMD__molfile__plugin__wrapper" ],
      [ "XTC_file", "classpteros_1_1XTC__file.html", "classpteros_1_1XTC__file" ],
      [ "XYZ_file", "classpteros_1_1XYZ__file.html", "classpteros_1_1XYZ__file" ]
    ] ]
];