var namespacepteros =
[
    [ "Atom", "classpteros_1_1Atom.html", "classpteros_1_1Atom" ],
    [ "Atom_proxy", "classpteros_1_1Atom__proxy.html", "classpteros_1_1Atom__proxy" ],
    [ "Consumer", "classpteros_1_1Consumer.html", "classpteros_1_1Consumer" ],
    [ "Consumer_base", "classpteros_1_1Consumer__base.html", "classpteros_1_1Consumer__base" ],
    [ "Data_container", "structpteros_1_1Data__container.html", "structpteros_1_1Data__container" ],
    [ "DCD_file", "classpteros_1_1DCD__file.html", "classpteros_1_1DCD__file" ],
    [ "Distance_search_within", "classpteros_1_1Distance__search__within.html", "classpteros_1_1Distance__search__within" ],
    [ "Energy_components", "structpteros_1_1Energy__components.html", "structpteros_1_1Energy__components" ],
    [ "Force_field", "classpteros_1_1Force__field.html", "classpteros_1_1Force__field" ],
    [ "Frame", "structpteros_1_1Frame.html", "structpteros_1_1Frame" ],
    [ "Frame_info", "structpteros_1_1Frame__info.html", "structpteros_1_1Frame__info" ],
    [ "GNM", "classpteros_1_1GNM.html", "classpteros_1_1GNM" ],
    [ "Grid", "classpteros_1_1Grid.html", "classpteros_1_1Grid" ],
    [ "GRO_file", "classpteros_1_1GRO__file.html", "classpteros_1_1GRO__file" ],
    [ "Gromacs_trajectory_file", "classpteros_1_1Gromacs__trajectory__file.html", "classpteros_1_1Gromacs__trajectory__file" ],
    [ "MOL2_file", "classpteros_1_1MOL2__file.html", "classpteros_1_1MOL2__file" ],
    [ "Mol_file", "classpteros_1_1Mol__file.html", "classpteros_1_1Mol__file" ],
    [ "Options", "classpteros_1_1Options.html", "classpteros_1_1Options" ],
    [ "PDB_file", "classpteros_1_1PDB__file.html", "classpteros_1_1PDB__file" ],
    [ "Periodic_box", "classpteros_1_1Periodic__box.html", "classpteros_1_1Periodic__box" ],
    [ "Pteros_error", "classpteros_1_1Pteros__error.html", "classpteros_1_1Pteros__error" ],
    [ "Q_file", "classpteros_1_1Q__file.html", "classpteros_1_1Q__file" ],
    [ "Selection", "classpteros_1_1Selection.html", "classpteros_1_1Selection" ],
    [ "Selection_parser", "classpteros_1_1Selection__parser.html", "classpteros_1_1Selection__parser" ],
    [ "System", "classpteros_1_1System.html", "classpteros_1_1System" ],
    [ "TNG_file", "classpteros_1_1TNG__file.html", "classpteros_1_1TNG__file" ],
    [ "Trajectory_processor", "classpteros_1_1Trajectory__processor.html", "classpteros_1_1Trajectory__processor" ],
    [ "TRR_file", "classpteros_1_1TRR__file.html", "classpteros_1_1TRR__file" ],
    [ "VMD_molfile_plugin_wrapper", "classpteros_1_1VMD__molfile__plugin__wrapper.html", "classpteros_1_1VMD__molfile__plugin__wrapper" ],
    [ "XTC_file", "classpteros_1_1XTC__file.html", "classpteros_1_1XTC__file" ],
    [ "XYZ_file", "classpteros_1_1XYZ__file.html", "classpteros_1_1XYZ__file" ]
];